fullstorydev/gosolr

solrmonitor/fifo.go
solrmonitor/fifo_test.go
solrmonitor/solrmonitor_test.go
solrmonitor/util_test.go
solrmonitor/zkdispatcher.go
solrmonitor/zkdispatcher_test.go

This should alleviate issues where the main channel (used to notify the event loop of a new watcher) becomes full. The event loop does much less work, so should have a much easier time keeping up with incoming requests. The actual processing is done in other goroutines.
This branch ensures serial delivery of events to a single callback. However, that was not actually necessary for any existing solrmonitor code because a single "callback" was just a handler for a single node/watch. And since watches are one-shot, events are guaranteed to be serial because a second event cannot be dispatched until after the first one is consumed and the handler re-registers itself. (I believe this code used to use a different goroutine per watch anyway, so the handlers are appropriately "thread-safe".)
I …

run dispatch handlers concurrently

---

solrmonitor/fifo.go
solrmonitor/fifo_test.go

This addresses a possible memory leak in the fifo queue.
Note that this isn't typically urgent in practice because once a queue quiesces, the dispatcher removes it completely (so the whole queue, and any possible remaining references, can be GCed).
But if there are a lot of workers and one or more queues start to get large-ish, this will ensure the process won't prematurely OOME.

cleanup queue entries after use

---

solrmonitor/zkdispatcher.go
solrmonitor/zkdispatcher_test.go

This also increases the buffer size of the channel used to send new watches to the event loop and doubles the time out. Hopefully this will help with the "channel full" panic that we've seen in anita and suggestive.

no mutex to add watch to dispatcher

---

solrmonitor/zkdispatcher.go

tests pass; I don't think we need the separate signal now that there's a close channel

just use the closed channel to signal closure

---

solrman/smservice/run.go

This allows other libraries that import smservice to inspect the current status

Add a method to expose the statusOp for a solrmanservice

---

go.mod
go.sum
smtestutil/zktestlogger.go
smutil/util.go
smutil/zkmutex.go
smutil/zkmutex_test.go
solrcheck/problems.go
solrcheck/problems_test.go
solrman/smstorage/zk_storage.go
solrman/smstorage/zk_storage_test.go
solrmonitor/main/solrmonitor/solrmonitor.go
solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go
solrmonitor/zkwatcherman.go

Use our fork for now to fix some session lost issues.
Additionally, update import package to reference new package name.

Update zk library to use our fork.

---

solrcheck/problems_test.go
solrmonitor/SolrEventListener.go
solrmonitor/collectionstate.go
solrmonitor/main/solrmonitor/solrmonitor.go
solrmonitor/mock.go
solrmonitor/replicastate.go
solrmonitor/shardstate.go
solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go
solrmonitor/util_test.go

1. Added 'SolrEventListener' to solrmonitor. Client can implement 'SolrEventListener' interface to receive the callbacks for all solr cluster change.
2. Our solrmonitor will implement this. 
3. Also, solrman will also implement this interface for event driven architecture.
4. This PR also includes PRS stuff as we were testing all these testcases.
5. (I am happy to schedule session to go through all those changes )

Hitesh solr event listener

---

smutil/zkmutex_test.go
solrman/smstorage/zk_storage_test.go
solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go

1. Organized locks more granular.
2. Collection state updated in collection's write lock
3. Fetch collection state in read lock- (it reflects the state between two goroutines)
4. (All zk events are recursive. And golang locks are not reentrant. So making sure each path has one level of lock only)
5. (On start => we get all collections => we spawn goroutine for each collection =>  that sees prs enable on collection => that subscribe for collection's state.json children => that fetches all children(prs state)). Thus making sure nothing recursively locks on initialization.

Added more granular read write lock

---

solrman/smstorage/inmemory_storage.go
solrman/smstorage/storage.go
solrman/smstorage/zk_storage.go
solrman/smstorage/zk_storage_test.go

This allows multiple callers to set independent disabled states on solrman; only once all disabled states are removed is it considered reenabled. Requests to disable solrman are keyed by the requestor. This is part of the auto-enabling uberseer design, as having multiple places that can disable solrman would lead to incorrect reenabling or blocking other requests without stacking disables.

multi-reasons for solrman disabled

---

solrman/smmodel/model.go

context: in spinning up a new cluster, there's orgs with fairly high traffic where they are thrashing the move algorithm. This is only a concern during the initial spinup of a cluster, but to that end, if a cluster is particularly underloaded (<10% of max data size), don't move for size reasons. Note: this will still allow moves for cluster balance reasons.

more friction for moves in underloaded clusters

---

solrman/smstorage/inmemory_storage.go
solrman/smstorage/storage.go
solrman/smstorage/zk_storage.go

These new methods will return the creation time for the split/move disabled path in Zookeeper. This will allow us to query to get the time since splits/moves were disabled to be able to use those for alerting in Solrman.

Adding methods for getting split/move disabled times

---

solrmonitor/solrmonitor.go

While searching for logs on BQ, I usually use `jsonPayload.message LIKE '%<collenction name>%'`, however it would miss the PRS state update message as it does not contain the collection name
Add the collection name as a part of the PRS update message

Improve solrman solrmonitor logging for prs

---

solrmonitor/replicastate.go

This PR adds Type to ReplicaState and two convienience methods: `IsPull` and `IsNRT`. The Type field is needed for High Availability to determine which replica is the NRT and which is the Pull replica.
Tested locally by printing out the ReplicaState from local solrman.

Add Type to ReplicaState

---

solrmonitor/mock.go

The current `SolrMonitor.GetLiveNodes` call checks
```
if c.zkCli.State() != zk.StateHasSession {
return nil, errors.New("not currently connected to zk")
}
```
which panics for existing `NewMockSolrMonitor` as zkCli is `nil`
Improve `NewMockSolrMonitor` to have a dummy zkCli which always returns `zk.StateHasSession` for `zkCli.State()`
This is necessary for writing unit test cases for solrman which calls `Cluster.GetLiveDataNode` which eventually delegates such call to `SolrMonitor`.

Improved mock solrmonitor to support `SolrMonitor.GetLiveNodes`

---

solrman/solrmanapi/request.go

The existing `MoveShardRequest` (a bit confusing in naming, it actually moves the replica of a shard) does not contain the actual name of the replica being moved. 
There are 2 issues:
1. If even momentarily a node has 2 replicas from the same shard (for example in the process of asynchronously swapping the PULL and NRT replicas between 2 nodes), the handler cannot tell which replica is it trying to move
2. Since the handler does not have such info, it would need to perform extra logic to locate the replica https://github.com/cowpaths/mn/blob/ea2e0be4b9e81f0a5f248ded4b53ca99e2ed32d2/projects/fullstory/go/src/fs/services/solrman/internal/solrmansvc/cluster.go#L573 , such might sometimes be unnecessary if the move analysis logic has already figured out which replica is the target
Added …

Add replica field for `MoveShardRequest`

---

solrmonitor/solrmonitor.go

This PR adds the GetOverseerNodes API to solrmonitor by parsing `roles.json`. This PR is necessary to enable using overseer nodes for admin operations in Solrman, and will be nice to have for any future code that requires knowing what the overseer nodes are.

Add GetOverseerNodes

---

solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go

I think its ok to remove now with solr 8.8. if we see any issue then I need to find some alternative for that

Removing cluster state file check from zk as it is removed from 9.0

---

smutil/util.go

Related to https://fullstory.atlassian.net/browse/SAI-4370 with attempts to use hostname in the node name instead of IPs.
Regardless of whether we go ahead with that change or not, it's still a good idea to improve our `ParseNodeName` and `GetHostName` methods to handle both IP and hostname in the `host` as in node name pattern `<host>:<port>_solr`
For `ParseNodeName`,  I believe the existing implementation that breaks the node name down with underscore should really work with hostname too (since hostname should not have underscores).
But it's probably more future proof to just trim away the suffix, and fix the terminology used in the code anyway. 
For `GetHostName`, we can invoke `net.ParseIP(host)` to check if the host part is an IP, if so, use the old logic, otherwise return the non IP …

Make smutil a bit more flexible to handle both IP and hostname in node name

---

solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go

https://fullstory.atlassian.net/browse/SAI-4423
In solr9, configname is part of state.json file
in solr8, configanme was data of collection name in zk

Fixed configname for collections with solr9

---

solrman/smmodel/model.go
solrman/smmodel/node.go
solrman/solrmanapi/cloudstatus.go

This allows for dynamically determining max node sizes instead of using hard coded values and potentially having nodes with different disk sizes.

Updating to use max size per node that is set in the model

---

solrmonitor/collectionstate.go
solrmonitor/solrmonitor.go
solrmonitor/util_test.go

In solr 93 type of following collection properties has been changed. In general, we don't use these properties thus removing for time being. Once we will move from solr92 to solr93, we will add that back.
1. replicationFactor changed from string to int
2. perReplicaState changed from string to bool
I have tested this with solr92 and solr93

Removed ReplicationFactor prop from collectionState

---

solrmonitor/main/solrmonitor/solrmonitor.go
solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go

It's found in various scenarios that system collections (eg `.sys.COORDINATOR-COLL-_FS7`) have triggered unexpected handling on higher level logic which does not expect such collection.
Therefore we are adding an init flag `includeSysCol` , and by default we will ignore those system collections with prefix `.sys.`

Add a flag includeSysCol (default as fault) to control whether system collections should be included in the handling

---

solrmonitor/SolrEventListener.go
solrmonitor/solrmonitor.go
solrmonitor/solrmonitor_test.go

We don't need this as we have new functionality `coordinator` nodes, which are part of live nodes. This callback is causing issue with our go-services, as it resets query nodes to empty

remove zk watching for live_query_nodes and listener

---

solrmonitor/collectionstate.go

`perReplicaState` was previously removed in https://github.com/fullstorydev/gosolr/pull/61 due to type incompatibility (string vs bool) between 9.2+ versions and earlier versions
Since all our envs are on 9.2+ now, we can add such `perReplicaState` back as bool

SAI-4651 : Added `perReplicaState` back to collectionstate.go

---

solrmonitor/main/solrmonitor/solrmonitor.go
solrmonitor/solrmonitor.go

In our usage, there are solr collections with certain suffixes that we want to ignore by SolrMonitor
Similar to a previous feature to ignore system collections, we added another param `ignoreSuffixes` for `SolrMonitor` instantiation. Adjusted signatures accordingly.

SAI-5104 : provide option to ignore collections with certain suffixes
